### ISSUE TITLE
having hard time running this training after 100th iteration. 

### ISSUE THREAD

**Issue by NihadShahriar** [techzizou/yolov4-custom_Training#2]
hey techzizou, i am the guy from youtube comment. I am new in this environment.
I was just trying to recreate my own version of code by following your instructions. i have taken some pictures of 5 peoples and i want to train it with yolo. I have changed the required config files accordingly as your colab notebook asked. i have to create a obj folder in darknet/data to save the unziped files as the code you provided was not creating that. I have provided some screenshots and a few modifications i have made in this process. please let me know.
![cfg1](https://user-images.githubusercontent.com/83898331/117562913-338eb080-b0c4-11eb-870e-da8de800e654.PNG)
![cfg2](https://user-images.githubusercontent.com/83898331/117562914-34bfdd80-b0c4-11eb-8816-3e41210094a8.PNG)
![cfg3](https://user-images.githubusercontent.com/83898331/117562915-34bfdd80-b0c4-11eb-9907-192cf846ba98.PNG)
![cfg4](https://user-images.githubusercontent.com/83898331/117562916-35587400-b0c4-11eb-8f09-4f6e80384d9d.PNG)
![mydrive yolov4](https://user-images.githubusercontent.com/83898331/117562917-35f10a80-b0c4-11eb-91c8-40e756813ad4.PNG)
![obj data](https://user-images.githubusercontent.com/83898331/117562919-3689a100-b0c4-11eb-969d-6bd0b9e5c511.PNG)
![obj name](https://user-images.githubusercontent.com/83898331/117562920-3689a100-b0c4-11eb-978d-092078b2b4fd.PNG)
![process py](https://user-images.githubusercontent.com/83898331/117562921-37223780-b0c4-11eb-917e-39423ce95e06.PNG)
![test fn](https://user-images.githubusercontent.com/83898331/117562922-37bace00-b0c4-11eb-8bcf-743d5d712b88.PNG)
![train fn](https://user-images.githubusercontent.com/83898331/117562925-37bace00-b0c4-11eb-8fed-b4a303fb1abb.PNG)
![unzip](https://user-images.githubusercontent.com/83898331/117562926-38536480-b0c4-11eb-84f2-9a1ce9a9fa5f.jpg)
![100th iteration](https://user-images.githubusercontent.com/83898331/117563980-4b1d6780-b0cb-11eb-96b1-7ed10796953c.PNG)

your opinion.

**Comment by techzizou** [comment]
okay, a couple of things I see at first glance are wrong. Clearly, u didn't follow my steps **CAREFULLY**. 

first, as I mentioned in my first comment to create a training folder which u said u did. multiple times. Your spelling is wrong. u created **_Training_** folder with a Capital T instead of **_training_** folder. Linux environments are case-sensitive.

second, why are u writing **_data/obj_** in the unzip command. The unzip command automatically creates a folder named **_obj_**. Writing **_data/obj_** would create another folder inside **_obj_** like **_data/obj/obj_** which wud mess up the paths mentioned in the commands and the scripts I have given.

**Comment by NihadShahriar** [comment]
You are right. I missed the T.
I have tried doing the step instead of using data/obj. But no obj folder was created and thus the unziped Files were saved in the data folder directly.

**Comment by techzizou** [comment]
ok np. make sure ur current working directory is the darknet directory when running the unzip command. I just ran it. it works fine. let me know if u have any other problems

**Comment by NihadShahriar** [comment]
The training is now working. Thanks a lot for your time and effort. Your videos made it much easier for me to do this. Thank you.😊
